// <auto-generated />
using System;
using Auniv.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Auniv.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250910171332_MudarProvinciaDeEnumParaString")]
    partial class MudarProvinciaDeEnumParaString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Auniv.Models.Curso", b =>
                {
                    b.Property<long>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdCurso"));

                    b.Property<string>("Duracao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("IdDepartamento")
                        .HasColumnType("bigint");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdCurso");

                    b.HasIndex("IdDepartamento");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("Auniv.Models.Departamento", b =>
                {
                    b.Property<long>("IdDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdDepartamento"));

                    b.Property<long>("IdUniversidade")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdDepartamento");

                    b.HasIndex("IdUniversidade");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("Auniv.Models.Universidade", b =>
                {
                    b.Property<long>("IdUniversidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdUniversidade"));

                    b.Property<DateOnly>("DataFundacao")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<long>("NumeroEstudantes")
                        .HasColumnType("bigint");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("SiteOficial")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("varchar(75)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdUniversidade");

                    b.HasIndex("Sigla")
                        .IsUnique();

                    b.ToTable("Universidades");
                });

            modelBuilder.Entity("Auniv.Models.Curso", b =>
                {
                    b.HasOne("Auniv.Models.Departamento", "Departamento")
                        .WithMany("Cursos")
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("Auniv.Models.Departamento", b =>
                {
                    b.HasOne("Auniv.Models.Universidade", "Universidade")
                        .WithMany("Departamentos")
                        .HasForeignKey("IdUniversidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universidade");
                });

            modelBuilder.Entity("Auniv.Models.Universidade", b =>
                {
                    b.OwnsOne("Auniv.Models.Localizacao", "Localizacao", b1 =>
                        {
                            b1.Property<long>("UniversidadeIdUniversidade")
                                .HasColumnType("bigint");

                            b1.Property<string>("Municipio")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Provincia")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("UniversidadeIdUniversidade");

                            b1.ToTable("Universidades");

                            b1.WithOwner()
                                .HasForeignKey("UniversidadeIdUniversidade");
                        });

                    b.Navigation("Localizacao")
                        .IsRequired();
                });

            modelBuilder.Entity("Auniv.Models.Departamento", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("Auniv.Models.Universidade", b =>
                {
                    b.Navigation("Departamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
